name: macro_concept
publish_to: none
environment:
  sdk: ">=3.6.0-0 <4.0.0"
dependencies:
  macros: ^0.1.0-main
  json: ^0.20.2 ##Right now it is not part of macro but implementation with macro
dev_dependencies:
  _fe_analyzer_shared: any
  args: ^2.3.0
  checks: ^0.2.0
  dart_style: ^2.2.1

 